package protocol

import (
	"encoding/binary"
	"errors"
)

// Message types — control (streamID = 0).
const (
	MsgHello    byte = 0x01
	MsgHelloOK  byte = 0x02
	MsgHelloErr byte = 0x03
	MsgPeerConn byte = 0x04
	MsgPeerGone byte = 0x05
	MsgSync     byte = 0x06
	MsgPing     byte = 0xF0
	MsgPong     byte = 0xF1
)

// Message types — stream (streamID > 0).
const (
	MsgOpen     byte = 0x10
	MsgOpenOK   byte = 0x11
	MsgOpenFail byte = 0x12
	MsgData     byte = 0x20
	MsgFin      byte = 0x21
	MsgRst      byte = 0x22
)

// Stream-ID layout (uint32, big-endian on the wire):
//
//	bits 31..24  helperShortID (1..255; 0 = unassigned / legacy)
//	bit  23      PROBE flag (1 = synthetic end-to-end-connectivity probe)
//	bits 22..0   localID (helper-side allocator, ~8.4 M values per helper)
//
// A probe stream is generated by the helper to verify that the wsApi data path
// reaches the adapter and the adapter can talk back. The adapter recognises
// the PROBE bit on OPEN, does NOT dial its configured target, and synthesises
// an HTTP/1.1 200 OK response so the helper can validate the round-trip.
const (
	StreamHelperShortIDShift = 24
	StreamProbeFlag          uint32 = 0x00800000
	StreamLocalIDMask        uint32 = 0x007FFFFF
)

// IsProbe reports whether a stream ID was minted as a connectivity probe.
func IsProbe(streamID uint32) bool { return streamID&StreamProbeFlag != 0 }

// HelperShortID extracts the helper short ID from a stream ID.
func HelperShortID(streamID uint32) byte { return byte(streamID >> StreamHelperShortIDShift) }

// Frame is a single protocol message.
// Wire: [1B type][4B streamID BE][4B seqID BE][payload...]
type Frame struct {
	Type     byte
	StreamID uint32
	SeqID    uint32
	Payload  []byte
}

// Encode serialises a Frame.
func Encode(f Frame) []byte {
	buf := make([]byte, 9+len(f.Payload))
	buf[0] = f.Type
	binary.BigEndian.PutUint32(buf[1:5], f.StreamID)
	binary.BigEndian.PutUint32(buf[5:9], f.SeqID)
	copy(buf[9:], f.Payload)
	return buf
}

// Decode parses a byte slice into a Frame.
func Decode(data []byte) (Frame, error) {
	if len(data) < 9 {
		return Frame{}, errors.New("frame too short")
	}
	return Frame{
		Type:     data[0],
		StreamID: binary.BigEndian.Uint32(data[1:5]),
		SeqID:    binary.BigEndian.Uint32(data[5:9]),
		Payload:  data[9:],
	}, nil
}

// EncodeHello builds a HELLO payload: [1B version][token UTF-8].
func EncodeHello(version byte, token string) []byte {
	t := []byte(token)
	buf := make([]byte, 1+len(t))
	buf[0] = version
	copy(buf[1:], t)
	return buf
}

// DecodeHello parses a HELLO payload.
func DecodeHello(payload []byte) (version byte, token string, err error) {
	if len(payload) < 1 {
		return 0, "", errors.New("HELLO payload too short")
	}
	return payload[0], string(payload[1:]), nil
}

// EncodeHelloOK builds a HELLO_OK payload:
// [2B ownIdLen][ownId][2B peerIdLen][peerId][2B tokenLen][iamToken][1B helperShortID?]
//
// helperShortID is appended only when nonzero (multi-helper mode). The cloud
// function assigns each helper a unique 1-byte ID 1..255 that the helper then
// stamps into the top byte of every streamID it allocates; this lets the
// adapter route per-stream frames back to the right helper. shortID==0 means
// "unassigned / legacy single-helper" — the helper allocates plain streamIDs.
// Adapter-bound HELLO_OK is fine with shortID==0; only helper-bound HELLO_OK
// carries a real value.
func EncodeHelloOK(ownID, peerID, iamToken string, helperShortID byte) []byte {
	o := []byte(ownID)
	p := []byte(peerID)
	t := []byte(iamToken)
	extra := 0
	if helperShortID != 0 {
		extra = 1
	}
	buf := make([]byte, 2+len(o)+2+len(p)+2+len(t)+extra)
	off := 0
	binary.BigEndian.PutUint16(buf[off:], uint16(len(o)))
	off += 2
	copy(buf[off:], o)
	off += len(o)
	binary.BigEndian.PutUint16(buf[off:], uint16(len(p)))
	off += 2
	copy(buf[off:], p)
	off += len(p)
	binary.BigEndian.PutUint16(buf[off:], uint16(len(t)))
	off += 2
	copy(buf[off:], t)
	off += len(t)
	if extra == 1 {
		buf[off] = helperShortID
	}
	return buf
}

// DecodeHelloOK parses a HELLO_OK payload. The trailing helperShortID byte is
// optional; if missing it is reported as 0 (legacy single-helper mode).
func DecodeHelloOK(payload []byte) (ownID, peerID, iamToken string, helperShortID byte, err error) {
	if len(payload) < 6 {
		return "", "", "", 0, errors.New("HELLO_OK payload too short")
	}
	off := 0
	oLen := int(binary.BigEndian.Uint16(payload[off:]))
	off += 2
	if off+oLen+2 > len(payload) {
		return "", "", "", 0, errors.New("HELLO_OK: bad ownID length")
	}
	ownID = string(payload[off : off+oLen])
	off += oLen

	pLen := int(binary.BigEndian.Uint16(payload[off:]))
	off += 2
	if off+pLen+2 > len(payload) {
		return "", "", "", 0, errors.New("HELLO_OK: bad peerID length")
	}
	peerID = string(payload[off : off+pLen])
	off += pLen

	tLen := int(binary.BigEndian.Uint16(payload[off:]))
	off += 2
	if off+tLen > len(payload) {
		return "", "", "", 0, errors.New("HELLO_OK: bad token length")
	}
	iamToken = string(payload[off : off+tLen])
	off += tLen

	// Optional trailing helperShortID byte (multi-helper mode).
	if off < len(payload) {
		helperShortID = payload[off]
	}
	return
}

// EncodePeerConn builds a PEER_CONN payload:
// [2B peerIdLen][peerId][2B tokenLen][iamToken][1B helperShortID?]
//
// helperShortID is appended only when nonzero. It is used in the
// cloud-function → adapter direction to identify which helper is announcing
// itself in multi-helper mode. adapter → helper PEER_CONN (telling a helper
// about the adapter) always omits it (single adapter; helpers don't need an
// adapter shortID).
func EncodePeerConn(peerID, iamToken string, helperShortID byte) []byte {
	p := []byte(peerID)
	t := []byte(iamToken)
	extra := 0
	if helperShortID != 0 {
		extra = 1
	}
	buf := make([]byte, 2+len(p)+2+len(t)+extra)
	off := 0
	binary.BigEndian.PutUint16(buf[off:], uint16(len(p)))
	off += 2
	copy(buf[off:], p)
	off += len(p)
	binary.BigEndian.PutUint16(buf[off:], uint16(len(t)))
	off += 2
	copy(buf[off:], t)
	off += len(t)
	if extra == 1 {
		buf[off] = helperShortID
	}
	return buf
}

// DecodePeerConn parses a PEER_CONN payload. The trailing helperShortID byte
// is optional; if missing it is reported as 0 (legacy single-helper mode).
func DecodePeerConn(payload []byte) (peerID, iamToken string, helperShortID byte, err error) {
	if len(payload) < 4 {
		return "", "", 0, errors.New("PEER_CONN payload too short")
	}
	off := 0
	pLen := int(binary.BigEndian.Uint16(payload[off:]))
	off += 2
	if off+pLen+2 > len(payload) {
		return "", "", 0, errors.New("PEER_CONN: bad peerID length")
	}
	peerID = string(payload[off : off+pLen])
	off += pLen

	tLen := int(binary.BigEndian.Uint16(payload[off:]))
	off += 2
	if off+tLen > len(payload) {
		return "", "", 0, errors.New("PEER_CONN: bad token length")
	}
	iamToken = string(payload[off : off+tLen])
	off += tLen

	if off < len(payload) {
		helperShortID = payload[off]
	}
	return
}

// EncodePeerGone builds a PEER_GONE payload. When helperShortID is nonzero it
// indicates that only that specific helper disconnected (adapter-bound, multi-
// helper mode). When zero, the payload is empty and means "the singleton peer
// is gone" (legacy / helper-bound).
func EncodePeerGone(helperShortID byte) []byte {
	if helperShortID == 0 {
		return nil
	}
	return []byte{helperShortID}
}

// DecodePeerGone returns the helperShortID from the payload, or 0 if the
// payload is empty (legacy / helper-bound).
func DecodePeerGone(payload []byte) byte {
	if len(payload) == 0 {
		return 0
	}
	return payload[0]
}

// EncodePong builds a PONG payload: [2B tokenLen][iamToken].
func EncodePong(iamToken string) []byte {
	t := []byte(iamToken)
	buf := make([]byte, 2+len(t))
	binary.BigEndian.PutUint16(buf[0:], uint16(len(t)))
	copy(buf[2:], t)
	return buf
}

// DecodePong parses a PONG payload.
func DecodePong(payload []byte) (iamToken string, err error) {
	if len(payload) < 2 {
		return "", errors.New("PONG payload too short")
	}
	tLen := int(binary.BigEndian.Uint16(payload[0:]))
	if 2+tLen > len(payload) {
		return "", errors.New("PONG: bad token length")
	}
	return string(payload[2 : 2+tLen]), nil
}
